### ISSUE TITLE
"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9090): Max retries exceeded with url:"  error occurs

### ISSUE THREAD

**Issue by moonsong98** [osamhack2021/CLOUD_WEB_Blo-my_Byzantium#14]
Error log is in picture below.
![2](https://user-images.githubusercontent.com/37493475/137583256-7f10819e-8ad7-4237-8844-091b6f5a5258.PNG)

**Comment by donggni0712** [comment]
hyperledger-fabric rest server 실행을  readme에 안적어놨었네요. 추가하였습니다.
하이퍼레저 서버다 실행시킨 후 
`cd /workspaces/CLOUD_WEB_Blo-my_Byzantium/fabric-samples/blomy/javascript
node rest.js`
도 하셔야됩니다.
